In [1]:
from pkg.db.query.sales import load_sales_data

In [2]:
sales_df = load_sales_data()

In [3]:
sales_df.head()

  product_fa product        date          provider       dep  boxq  sales
0     آبیرال  Abiral  140301      اسپاد فارمد دارو  نفرولوژی   NaN    0.0
1     آبیرال  Abiral  140302      اسپاد فارمد دارو  نفرولوژی   NaN    0.0
2     آبیرال  Abiral  140303      اسپاد فارمد دارو  نفرولوژی   NaN    0.0
3     آبیرال  Abiral  140304      اسپاد فارمد دارو  نفرولوژی   NaN    0.0
4     آبیرال  Abiral  140305      اسپاد فارمد دارو  نفرولوژی   NaN    0.0

In [8]:
sales_df.tail()

,product_fa,product,date,provider,dep,boxq,sales
31322,زیتاکس 500,Zytux 500,140503,آریوژن,انکولوژی بیولوژیک,NaN,0.0
31323,زیتاکس 500,Zytux 500,140504,آریوژن,انکولوژی بیولوژیک,1.0,13788.0
31324,زیتاکس 500,Zytux 500,140504,آریوژن,انکولوژی بیولوژیک,NaN,0.0
31325,زیتاکس 500,Zytux 500,140505,آریوژن,انکولوژی بیولوژیک,1.0,5991.0
31326,زیتاکس 500,Zytux 500,140505,آریوژن,انکولوژی بیولوژیک,NaN,0.0